[versions]

# Common
kotlin = "2.2.21"

#  Plugins
ktlint-plugin = "14.0.1"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = {id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin"}

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
